#!/usr/bin/env python3

import argparse

from lib.facade import run

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Resurrect the Evolution')
    parser.add_argument('--name', type=str, help='Language name', required=True)
    parser.add_argument('--grammar', type=str, help='Grammar file name', required=True)
    parser.add_argument('--abc', type=str, help='ABC file name', required=True)
    parser.add_argument('--dict', type=str, help='Dictionary file name', required=True)
    parser.add_argument('--text', type=str, nargs='+', help='Any text file (input_file:output_file)', required=True)

    args = parser.parse_args()

    text_filenames = []
    for names in args.text:
        filenames = names.split(':', 2)
        if len(filenames) < 2:
            print('--text argument is not valid')
            exit()
        text_filenames.append(filenames)

    run(args.name, args.grammar, args.abc, args.dict, text_filenames)
